### ISSUE TITLE
possible improvement to _pgbouncer.ini.tpl

### ISSUE THREAD

**Issue by matth-boise** [cradlepoint/kubernetes-helm-chart-pgbouncer#10]
should _pgbouncer.ini.tpl change how it generates each "databases" line?  currently does
```
{{ $k }} = host={{ $v.host }} port={{ $v.port }} {{ if $v.user }}user={{ $v.user }}{{end}} dbname={{ $v.dbname }}
```
but maybe it should be:
```
{{ $v.dbname }} = host={{ $v.host }} port={{ $v.port }} {{ if $v.user }}user={{ $v.user }}{{end}} dbname={{ $v.dbname }}
```
(so it doesn't matter what the name of each databases.xxx: map is)

**Comment by mattmessinger** [comment]
@matth-boise any updates on this?  should we close it out?

**Comment by matth-boise** [comment]
i'd like to leave this open

**Comment by matth-boise** [comment]
already done - closing issue
