### ISSUE TITLE
chart version 1.0.6 release is missing service template

### ISSUE THREAD

**Issue by teejaded** [cradlepoint/kubernetes-helm-chart-pgbouncer#22]
```
curl -sL https://github.com/cradlepoint/kubernetes-helm-chart-pgbouncer/releases/download/1.0.6/pgbouncer-1.0.6.tgz -o - | tar -t
pgbouncer/Chart.yaml
pgbouncer/values.yaml
pgbouncer/templates/NOTES.txt
pgbouncer/templates/_helpers.tpl
pgbouncer/templates/_pgbouncer.ini.tpl
pgbouncer/templates/_userlist.txt.tpl
pgbouncer/templates/deployment-pgbouncer.yaml
pgbouncer/templates/pod-disruption-budget.yaml
pgbouncer/templates/secret-pgbouncer-configfiles.yaml
pgbouncer/.helmignore
```

**Comment by matth-boise** [comment]
@teejaded the service to select this pgbouncer was intentionally omitted from this chart to give calling charts flexibility.  (e.g., calling charts can create a common foo-postgresql Service that either selects pgbouncer pods created by this chart -- or it is an ExternalName that points to some external database that does not require connection pooling)  likely, documenting this would be a good addition.  as well as optionally creating a Service to select pods created by deployment-pgbouncer.yaml

**Comment by matth-boise** [comment]
@teejaded fyi, a service.yaml is in process of being added

**Comment by mattmessinger** [comment]
@teejaded please try the 1.0.7 release.
